// Code generated by mockery v1.0.0
package mocks

import (
	models "go-crud-api/pkg/models/cats"

	mock "github.com/stretchr/testify/mock"
)

// IPlayerRepository is an autogenerated mock type for the IPlayerRepository type
type IPlayerRepository struct {
	mock.Mock
}

// GetPlayerByName provides a mock function with given fields: name
func (_m *IPlayerRepository) GetCatsById(id int) (models.Cats, error) {
	ret := _m.Called(id)

	var r0 models.Cats
	if rf, ok := ret.Get(0).(func(int) models.Cats); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Cats)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
