// Code generated by mockery v1.0.0
package mocks

import (
	data "go-crud-api/pkg/data/cats/data"

	mock "github.com/stretchr/testify/mock"
)

// IPlayerService is an autogenerated mock type for the IPlayerService type
type ICatService struct {
	mock.Mock
}

// GetScores provides a mock function with given fields: player1Name, player2Name
func (_m *ICatService) GetCatsById(id int) (data.CatsData, error) {
	ret := _m.Called(id)

	var r0 data.CatsData
	if rf, ok := ret.Get(0).(func(int) data.CatsData); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(data.CatsData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
